const ALL_QUOTES = [
  // --- AYANOKOJI KIYOTAKA (Classroom of the Elite) ---
  { q: "All people are nothing but tools. It doesn't matter how its done. It doesn't matter what needs to be sacrificed. In this world, winning is everything.", a: "Ayanokoji Kiyotaka" },
  { q: "Equality is a myth. A lie told to those who cannot stand on their own.", a: "Ayanokoji Kiyotaka" },
  { q: "The only thing that matters is the result. The process is just noise.", a: "Ayanokoji Kiyotaka" },
  { q: "True strength is hidden. To reveal it is to lose the advantage.", a: "Ayanokoji Kiyotaka" },
  { q: "Confession is not about seeking forgiveness; it is about lightening the burden of the heart.", a: "Ayanokoji Kiyotaka" },
  { q: "Freedom is a burden that most people don't know how to carry.", a: "Ayanokoji Kiyotaka" },
  { q: "I have never once thought of you as an ally. Not you, not Kushida, not Hirata.", a: "Ayanokoji Kiyotaka" },
  { q: "If you want to protect something, you must be willing to destroy everything else.", a: "Ayanokoji Kiyotaka" },
  { q: "The world is not a kind place. It is a chessboard where the weak are sacrificed.", a: "Ayanokoji Kiyotaka" },
  { q: "Sometimes the most dangerous person is the one who says nothing.", a: "Ayanokoji Kiyotaka" },
  { q: "I don't care about the past. I only care about the present and the future I choose.", a: "Ayanokoji Kiyotaka" },
  { q: "Emotions are just biological reactions that can be manipulated.", a: "Ayanokoji Kiyotaka" },
  { q: "To understand others, you must first understand yourself. But most people are too afraid to look.", a: "Ayanokoji Kiyotaka" },
  { q: "Cooperation is just a form of mutual exploitation.", a: "Ayanokoji Kiyotaka" },
  { q: "There is no such thing as a fair fight. Only those who prepare and those who lose.", a: "Ayanokoji Kiyotaka" },
  { q: "A smile can be the deadliest weapon in an arsenal.", a: "Ayanokoji Kiyotaka" },
  { q: "People will always reveal their true nature when they are cornered.", a: "Ayanokoji Kiyotaka" },
  { q: "Knowledge is power, but the application of knowledge is mastery.", a: "Ayanokoji Kiyotaka" },
  { q: "I choose the path of least resistance, until resistance becomes necessary.", a: "Ayanokoji Kiyotaka" },
  { q: "Victory is not a goal; it is a requirement.", a: "Ayanokoji Kiyotaka" },
  { q: "Fear is a useful tool, but only if you aren't the one feeling it.", a: "Ayanokoji Kiyotaka" },
  { q: "The difference between a genius and a fool is the ability to hide one's true intentions.", a: "Ayanokoji Kiyotaka" },
  { q: "The impediment to action advances action. What stands in the way becomes the way.", a: "Marcus Aurelius" },
  { q: "Trust is a luxury I cannot afford.", a: "Ayanokoji Kiyotaka" },
  { q: "The heart is the most fragile part of a human being.", a: "Ayanokoji Kiyotaka" },
  { q: "Isolation is a sanctuary for the mind.", a: "Ayanokoji Kiyotaka" },
  { q: "Every action has a consequence. Some just take longer to appear.", a: "Ayanokoji Kiyotaka" },
  { q: "Human nature is fundamentally selfish. Once you accept that, everything becomes clear.", a: "Ayanokoji Kiyotaka" },
  { q: "I am neither a hero nor a villain. I am just a survivor.", a: "Ayanokoji Kiyotaka" },
  { q: "The strongest weapon is the one you don't even know you're holding.", a: "Ayanokoji Kiyotaka" },
  { q: "To win, you must be willing to lose everything.", a: "Ayanokoji Kiyotaka" },
  { q: "Silence is often the best answer to a fool's question.", a: "Ayanokoji Kiyotaka" },
  { q: "The mind is a battlefield where only the strongest survive.", a: "Ayanokoji Kiyotaka" },
  { q: "Empathy is a weakness that can be exploited.", a: "Ayanokoji Kiyotaka" },
  { q: "The truth is rarely what people want to hear.", a: "Ayanokoji Kiyotaka" },
  { q: "Success is built on a foundation of failures that others never see.", a: "Ayanokoji Kiyotaka" },
  { q: "A leader is someone who can sacrifice themselves for the result.", a: "Ayanokoji Kiyotaka" },
  { q: "The world is a stage, and most people are just extras.", a: "Ayanokoji Kiyotaka" },
  { q: "To be free, you must first be strong.", a: "Ayanokoji Kiyotaka" },
  { q: "Logic is the only reliable guide in a world of chaos.", a: "Ayanokoji Kiyotaka" },
  { q: "People are predictable when you know their desires.", a: "Ayanokoji Kiyotaka" },
  { q: "The only limit is the one you place on yourself.", a: "Ayanokoji Kiyotaka" },
  { q: "I don't need friends. I need results.", a: "Ayanokoji Kiyotaka" },
  { q: "The past is a ghost that only haunts those who look back.", a: "Ayanokoji Kiyotaka" },
  { q: "Winning is a habit. So is losing.", a: "Ayanokoji Kiyotaka" },
  { q: "Strength is not just physical. It is mental and emotional as well.", a: "Ayanokoji Kiyotaka" },
  { q: "The most important lessons are the ones you learn by yourself.", a: "Ayanokoji Kiyotaka" },
  { q: "I will do whatever it takes to achieve my goals.", a: "Ayanokoji Kiyotaka" },
  { q: "The only constant in this world is change.", a: "Ayanokoji Kiyotaka" },
  { q: "My freedom begins where your control ends.", a: "Ayanokoji Kiyotaka" },

  // --- DRACULE MIHAWK (One Piece) ---
  { q: "It is the weight of one's resolve, not the edge of the blade, that determines the victor.", a: "Dracule Mihawk" },
  { q: "A sword with no edge is just a piece of metal. A soul with no purpose is just a ghost.", a: "Dracule Mihawk" },
  { q: "Only a fool fights a battle he cannot win. But only a legend wins a battle he shouldn't have fought.", a: "Dracule Mihawk" },
  { q: "I do not go hunting rabbits with a cannon.", a: "Dracule Mihawk" },
  { q: "True strength is the ability to know when to unsheathe your sword.", a: "Dracule Mihawk" },
  { q: "The world is full of people who talk about strength, but few who actually possess it.", a: "Dracule Mihawk" },
  { q: "A true swordsman never lets his emotions cloud his judgment.", a: "Dracule Mihawk" },
  { q: "A life without discipline is like a ship without a rudder, destined to be shattered by the first storm it encounters.", a: "Dracule Mihawk" },
  { q: "I have no interest in those who do not have the resolve to die for their dreams.", a: "Dracule Mihawk" },
  { q: "A blade is only as strong as the one who wields it.", a: "Dracule Mihawk" },
  { q: "Peace is a luxury that only the strong can afford.", a: "Dracule Mihawk" },
  { q: "The greatest victory is the one won without drawing blood.", a: "Dracule Mihawk" },
  { q: "I travel alone because most people cannot keep up with me.", a: "Dracule Mihawk" },
  { q: "Every scar is a lesson learned. Every victory is a step towards the peak.", a: "Dracule Mihawk" },
  { q: "The title of the world's strongest is a heavy burden to carry.", a: "Dracule Mihawk" },
  { q: "I do not seek fame. I seek the truth of the sword.", a: "Dracule Mihawk" },
  { q: "The sky is the only limit for those who have the courage to fly.", a: "Dracule Mihawk" },
  { q: "A true master is always a student.", a: "Dracule Mihawk" },
  { q: "The power of a swordsman is not in the size of his blade, but in the precision of his strike.", a: "Dracule Mihawk" },
  { q: "I have seen many things in this world, but few have impressed me.", a: "Dracule Mihawk" },
  { q: "The path to the top is paved with the bodies of those who failed.", a: "Dracule Mihawk" },
  { q: "I am not a hero. I am just a man who followed his own path.", a: "Dracule Mihawk" },
  { q: "A sword is an extension of the soul.", a: "Dracule Mihawk" },
  { q: "True power is not something you are born with. It is something you earn.", a: "Dracule Mihawk" },
  { q: "The only person I compete with is the man I was yesterday.", a: "Dracule Mihawk" },
  { q: "I do not fear death. I fear living a life without meaning.", a: "Dracule Mihawk" },
  { q: "The world is a vast ocean of possibilities. It is up to you to navigate it.", a: "Dracule Mihawk" },
  { q: "A true warrior never gives up, even when the odds are against him.", a: "Dracule Mihawk" },
  { q: "I have found peace in the solitude of the sea.", a: "Dracule Mihawk" },
  { q: "The wind carries the whispers of the past. The ocean carries the dreams of the future.", a: "Dracule Mihawk" },
  { q: "Every strike must be made with the intention to end the fight.", a: "Dracule Mihawk" },
  { q: "I have no room for those who do not respect the sword.", a: "Dracule Mihawk" },
  { q: "A master of the sword is a master of himself.", a: "Dracule Mihawk" },
  { q: "I seek a challenge that will make my heart race again.", a: "Dracule Mihawk" },
  { q: "Solitude is not an escape, but a crucible where the spirit is forged in the absence of noise.", a: "Dracule Mihawk" },
  { q: "True mastery is not found in the destruction of others, but in the absolute command over one's own impulses.", a: "Dracule Mihawk" },
  { q: "A true friend is someone who can look you in the eye and tell you the truth.", a: "Dracule Mihawk" },
  { q: "I do not need an army. I only need my sword.", a: "Dracule Mihawk" },
  { q: "The silence of the sea is the most beautiful music I have ever heard.", a: "Dracule Mihawk" },
  { q: "I am the master of my own destiny.", a: "Dracule Mihawk" },
  { q: "A sword is not just for killing. It is for protecting what is precious.", a: "Dracule Mihawk" },
  { q: "True strength is hidden in the quiet moments of life.", a: "Dracule Mihawk" },
  { q: "The sun will rise again, no matter how dark the night was.", a: "Dracule Mihawk" },
  { q: "I am a wanderer in a world that has forgotten how to dream.", a: "Dracule Mihawk" },
  { q: "A true swordsman never looks back at the blood he has shed.", a: "Dracule Mihawk" },
  { q: "I seek the ultimate truth of the sword.", a: "Dracule Mihawk" },
  { q: "The power to change the world is within your grasp.", a: "Dracule Mihawk" },
  { q: "I am the strongest, but I am still learning.", a: "Dracule Mihawk" },
  { q: "The world is waiting for those who are brave enough to take it.", a: "Dracule Mihawk" },
  { q: "I am Dracule Mihawk, and my sword will carve a path to the future.", a: "Dracule Mihawk" },

  // --- SUN TZU (The Art of War) ---
  { q: "Appear weak when you are strong, and strong when you are weak.", a: "Sun Tzu" },
  { q: "The supreme art of war is to subdue the enemy without fighting.", a: "Sun Tzu" },
  { q: "All warfare is based on deception.", a: "Sun Tzu" },
  { q: "If you know the enemy and know yourself, you need not fear the result of a hundred battles.", a: "Sun Tzu" },
  { q: "In the midst of chaos, there is also opportunity.", a: "Sun Tzu" },
  { q: "Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win.", a: "Sun Tzu" },
  { q: "He who is prudent and lies in wait for an enemy who is not, will be victorious.", a: "Sun Tzu" },
  { q: "To know your enemy, you must become your enemy.", a: "Sun Tzu" },
  { q: "The greatest victory is that which requires no battle.", a: "Sun Tzu" },
  { q: "Even the finest sword plunged into salt water will eventually rust.", a: "Sun Tzu" },
  { q: "Know yourself and you will win all battles.", a: "Sun Tzu" },
  { q: "Keep your friends close, and your enemies closer.", a: "Sun Tzu" },
  { q: "Invincibility lies in the defence; the possibility of victory in the attack.", a: "Sun Tzu" },
  { q: "Treat your men as you would your own beloved sons. And they will follow you into the deepest valley.", a: "Sun Tzu" },
  { q: "There is no instance of a nation benefitting from prolonged warfare.", a: "Sun Tzu" },
  { q: "The clever combatant imposes his will on the enemy, but does not allow the enemy's will to be imposed on him.", a: "Sun Tzu" },
  { q: "Opportunities multiply as they are seized.", a: "Sun Tzu" },
  { q: "When the enemy is relaxed, make them toil. When full, starve them. When settled, make them move.", a: "Sun Tzu" },
  { q: "Strategy without tactics is the slowest route to victory. Tactics without strategy is the noise before defeat.", a: "Sun Tzu" },
  { q: "If your enemy is secure at all points, be prepared for him. If he is in superior strength, evade him.", a: "Sun Tzu" },
  { q: "The quality of decision is like the well-timed swoop of a falcon which enables it to strike and destroy its victim.", a: "Sun Tzu" },
  { q: "Engage people with what they expect; it is what they are able to discern and confirms their projections. It keeps them settled while you anticipate the next move.", a: "Sun Tzu" },
  { q: "Let your plans be dark and impenetrable as night, and when you move, fall like a thunderbolt.", a: "Sun Tzu" },
  { q: "Wheels of justice grind slow but grind fine.", a: "Sun Tzu" },
  { q: "He will win who knows when to fight and when not to fight.", a: "Sun Tzu" },
  { q: "In wait for the enemy's arrival, I shall be ready.", a: "Sun Tzu" },
  { q: "The whole secret lies in confusing the enemy, so that he cannot fathom our real intent.", a: "Sun Tzu" },
  { q: "Be extremely subtle, even to the point of formlessness. Be extremely mysterious, even to the point of soundlessness. Thereby you can be the director of the opponent's fate.", a: "Sun Tzu" },
  { q: "Attack him where he is unprepared, appear where you are not expected.", a: "Sun Tzu" },
  { q: "Victory comes from finding the advantage in the disadvantage.", a: "Sun Tzu" },
  { q: "The enlightened ruler is heedful, and the good general full of caution.", a: "Sun Tzu" },
  { q: "If you are far from the enemy, make him believe you are near.", a: "Sun Tzu" },
  { q: "Move swift as the Wind and closely-formed as the Wood. Attack like the Fire and be still as the Mountain.", a: "Sun Tzu" },
  { q: "One may know how to conquer without being able to do it.", a: "Sun Tzu" },
  { q: "A leader leads by example, not by force.", a: "Sun Tzu" },
  { q: "Great results can be achieved with small forces.", a: "Sun Tzu" },
  { q: "Ponder and deliberate before you make a move.", a: "Sun Tzu" },
  { q: "Rewards for good service should not be deferred a single day.", a: "Sun Tzu" },
  { q: "The skillful employer of men will employ the wise man, the brave man, the covetous man, and the stupid man.", a: "Sun Tzu" },
  { q: "Plan for what it is difficult while it is easy, do what is great while it is small.", a: "Sun Tzu" },
  { q: "Do not repeat the tactics which have gained you one victory, but let your methods be regulated by the infinite variety of circumstances.", a: "Sun Tzu" },
  { q: "If quick, you can survive. If slow, you will perish.", a: "Sun Tzu" },
  { q: "To see victory only when it is within the ken of the common herd is not the acme of excellence.", a: "Sun Tzu" },
  { q: "Rouse him, and learn the principle of his activity or inactivity. Force him to reveal himself, so as to find out his vulnerable spots.", a: "Sun Tzu" },
  { q: "Disorder came from order, fear came from courage, weakness came from strength.", a: "Sun Tzu" },
  { q: "He who knows when he can fight and when he cannot, will be victorious.", a: "Sun Tzu" },
  { q: "The consummate leader cultivates the moral law, and strictly adheres to method and discipline; thus it is in his power to control success.", a: "Sun Tzu" },
  { q: "When you surround an army, leave an outlet free. Do not press a desperate foe too hard.", a: "Sun Tzu" },
  { q: "If the mind is willing, the flesh could go on and on without many things.", a: "Sun Tzu" },
  { q: "If you wait by the river long enough, the bodies of your enemies will float by.", a: "Sun Tzu" },

  // --- AI SELECTION (Life & Growth) ---
  { q: "The only person you should try to be better than is the person you were yesterday.", a: "Antigravity" },
  { q: "Consistency is more important than intensity. Small steps lead to giant leaps.", a: "Antigravity" },
  { q: "Your mind is a garden. Your thoughts are the seeds. You can grow flowers, or you can grow weeds.", a: "Antigravity" },
  { q: "Don't let the noise of others' opinions drown out your own inner voice.", a: "Antigravity" },
  { q: "The best time to plant a tree was 20 years ago. The second best time is now.", a: "Antigravity" },
  { q: "Hardships often prepare ordinary people for an extraordinary destiny.", a: "Antigravity" },
  { q: "Discipline is choosing between what you want now and what you want most.", a: "Antigravity" },
  { q: "You don't have to be great to start, but you have to start to be great.", a: "Antigravity" },
  { q: "Happiness is not something ready made. It comes from your own actions.", a: "Antigravity" },
  { q: "The secret of getting ahead is getting started.", a: "Antigravity" },
  { q: "Everything you've ever wanted is on the other side of fear.", a: "Antigravity" },
  { q: "It's not about having time, it's about making time.", a: "Antigravity" },
  { q: "Failure is not the opposite of success; it's part of success.", a: "Antigravity" },
  { q: "Your habits define your future. Choose them wisely.", a: "Antigravity" },
  { q: "Be kind to yourself. You are doing the best you can.", a: "Antigravity" },
  { q: "Focus on the solution, not the problem.", a: "Antigravity" },
  { q: "Don't compare your Chapter 1 to someone else's Chapter 20.", a: "Antigravity" },
  { q: "Believe you can and you're halfway there.", a: "Antigravity" },
  { q: "Success is the sum of small efforts, repeated day in and day out.", a: "Antigravity" },
  { q: "The only way to do great work is to love what you do.", a: "Antigravity" },
  { q: "Don't count the days, make the days count.", a: "Antigravity" },
  { q: "Your only limit is your mind.", a: "Antigravity" },
  { q: "Action is the foundational key to all success.", a: "Antigravity" },
  { q: "Do what you can, with what you have, where you are.", a: "Antigravity" },
  { q: "The future belongs to those who believe in the beauty of their dreams.", a: "Antigravity" },
  { q: "It always seems impossible until it's done.", a: "Antigravity" },
  { q: "Your vibe attracts your tribe.", a: "Antigravity" },
  { q: "Stay hungry, stay foolish.", a: "Antigravity" },
  { q: "Change your thoughts and you change your world.", a: "Antigravity" },
  { q: "Kindness is a language which the deaf can hear and the blind can see.", a: "Antigravity" },
  { q: "What you get by achieving your goals is not as important as what you become by achieving your goals.", a: "Antigravity" },
  { q: "The only real mistake is the one from which we learn nothing.", a: "Antigravity" },
  { q: "Difficult roads often lead to beautiful destinations.", a: "Antigravity" },
  { q: "Don't stop when you're tired. Stop when you're done.", a: "Antigravity" },
  { q: "If you want to fly, you have to give up the things that weigh you down.", a: "Antigravity" },
  { q: "The expert in anything was once a beginner.", a: "Antigravity" },
  { q: "Life is 10% what happens to us and 90% how we react to it.", a: "Antigravity" },
  { q: "Do something today that your future self will thank you for.", a: "Antigravity" },
  { q: "The grass is greener where you water it.", a: "Antigravity" },
  { q: "Work hard in silence, let your success be your noise.", a: "Antigravity" },
  { q: "A journey of a thousand miles begins with a single step.", a: "Antigravity" },
  { q: "Dream big and dare to fail.", a: "Antigravity" },
  { q: "The way to get started is to quit talking and begin doing.", a: "Antigravity" },
  { q: "The purpose of our lives is to be happy.", a: "Antigravity" },
  { q: "Get busy living or get busy dying.", a: "Antigravity" },
  { q: "You only live once, but if you do it right, once is enough.", a: "Antigravity" },
  { q: "Life is what happens when you're busy making other plans.", a: "Antigravity" },
  { q: "Stay positive, work hard, make it happen.", a: "Antigravity" },
  { q: "Do one thing every day that scares you.", a: "Antigravity" },
  { q: "Keep your face always toward the sunshine—and shadows will fall behind you.", a: "Antigravity" }
];
